---

- hosts: localhost
  become: true
  become_method: sudo
  become_user: lars
  connection: local
  tasks:
    - name: install cli stuff
      apt: name="{{item}}" state=present
      with_items:
        - terminator 
  roles:
    - dotfiles-rcm      
    - ohmyzsh
    - ansible-vundle

