---

- hosts: localhost
  become: true
  become_method: sudo
  become_user: lars
  connection: local
  tasks:
    - name: install cli stuff
      apt: name="{{item}}" state=present
      with_items:
        - terminator 
        - vim
        - curl
        - exfat-fuse
        - exfat-utils
        - tlp
        - tlp-rdw
        - powertop
    - name: Ensure laptop-mode-tools absent
      apt: name="laptop-mode-tools" state=absent
    - name: Create private projects dir
      file: path=~/projects/private state=directory
    - name: Create work projects dir
      file: path=~/projects/work state=directory

  roles:
    - dotfiles-rcm      
    - ohmyzsh
    - ansible-vundle

