---

- hosts: localhost
  connection: local
  tasks:
    - name: install cli stuff
      sudo: yes
      apt: name="{{item}}" state=present
      with_items:
        - terminator 
  roles:
    - dotfiles-rcm      
    - ansible-vundle

