---

- hosts: localhost
  connection: local
  pre_tasks:
    - name: install vim
      apt:
        name: vim
        state: present
  tasks:
    - name: install cli stuff
      apt: name="{{item}}" state=present
      with_items:
        - terminator 
        - curl
        - exfat-fuse
        - exfat-utils
        - tlp
        - tlp-rdw
        - powertop
    - name: Ensure laptop-mode-tools absent
      apt: name="laptop-mode-tools" state=absent
    - name: Create private projects dir
      file: path=~/projects/private state=directory
    - name: Create work projects dir
      file: path=~/projects/work state=directory

  roles:
    - dotfiles-rcm      
    - ohmyzsh
    - ansible-vundle

