---

- hosts: localhost
  connection: local
  sudo: yes
  tasks:
    - name: install common desktop apps and tweaks
      sudo: yes
      apt: name="{{item}}" state=present
      with_items:
        - keepassx
        - python-gpgme
  roles:
    - wtanaka.dropbox
    - { role: cmprescott.chrome, become: yes }
