---

- hosts: localhost
  become: true
  become_method: sudo
  connection: local
  tasks:
    - name: install common desktop apps and tweaks
      apt: name="{{item}}" state=present
      with_items:
        - keepassx
        - python-gpgme
        - clipit
  roles:
    - wtanaka.dropbox
    - { role: cmprescott.chrome }
