---

- hosts: localhost
  become: true
  become_method: sudo
  connection: local
  tasks:
    - name: install common desktop apps and tweaks
      apt: name="{{item}}" state=present
      with_items:
        - keepassx
        - python-gpgme
        - clipit
    - name: remove unwanted default ubuntu software
      apt: name="{{item}}" state=absent
      with_items:
        - unity-webapps-common
        - app-install-data-partner
  roles:
    - wtanaka.dropbox
    - { role: cmprescott.chrome }
