---

- hosts: localhost
  connection: local
  tasks:
    - name: install common desktop apps and tweaks
      apt: name="{{item}}" state=present
      with_items:
        - keepassx
        - python-gpgme
        - clipit
        - pavucontrol
        - brasero
        - indicator-keylock
        - network-manager-openvpn
        - network-manager-openvpn-gnome
        - network-manager-pptp
        - network-manager-pptp-gnome
        - network-manager-vpnc 
        - network-manager-vpnc-gnome
        - network-manager-openconnect
        - network-manager-openconnect-gnome
        - redshift-gtk
        - flashplugin-installer
    - name: remove unwanted default ubuntu software
      apt: name="{{item}}" state=absent
      with_items:
        - unity-webapps-common
        - app-install-data-partner
  roles:
    - wtanaka.dropbox
    - cmprescott.chrome
