---

- hosts: localhost
  connection: local
  vars:
    ij_download_dir: /home/lars/Downloads

  tasks:
    - name: mysql client
      apt: name="{{item}}" state=present
      with_items:
        - mysql-client
        - cmake
        - build-essential
        - python-dev
        - libxml2-dev
        - libxslt-dev
        - meld

  roles:
    - williamyeh.oracle-java
    - { role: rdeknijf.intellij, intellij_version: '2017.1', intellij_download_dir: "{{ ij_download_dir }}" }
    - git-latest
    - andrewrothstein.hub
