---

- hosts: localhost
  connection: local
  sudo: yes
  vars:
    ij_download_dir: /home/lars/Downloads
  roles:
    - williamyeh.oracle-java
    - { role: rdeknijf.intellij, intellij_version: 2016.3, intellij_download_dir: "{{ ij_download_dir }}" }
    - kbrebanov.git
