---

- name: add rcm repo
  apt_repository:
    repo: 'ppa:martin-frost/thoughtbot-rcm'
    state: present 
- name: install cli stuff
  apt: name="{{item}}" state=present
  with_items:
      - rcm
- name: get dotfiles
  git:
    repo: https://github.com/kiltec/.dotfiles.git
    dest: "{{ dotfiles_dir }}" 
    accept_hostkey: yes 
- name: symlink dotfiles using rcm
  shell: env RCRC=$HOME/dotfiles/rcrc rcup
  args:
    chdir: /home/lars 
    creates: .rcrc
